# -*- coding: utf-8 -*-
"""Jagadishwaran Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYOoUBaWmYSd9zgXTejbHHVur5HWTz13

# Project Title

## Employee Data Analysis & Worforce Performance Analytics

# **Objective(Problem statment)**
 To analyze employee demographics and workforce characteristics.To evaluate employee distribution across departments and regions.
To analyze employee salary patterns and identify factors affecting compensation.
To evaluate employee performance and identify performance trends.
To analyze employee status such as Active, Inactive, and Pending.
To compare remote and non-remote employees.
To identify relationships between employee age, salary, department, region, performance, and work mode.
To generate actionable insights that support data-driven HR and workforce decisions.
To help organizations improve employee performance, workforce planning, compensation

# Outcome

The project helps uncover important patterns and trends in employee demographics, salaries, departments, regions, performance, employment status, and remote-work arrangements.The analysis provides a clear understanding of workforce characteristics and employee performance, supporting evidence-based HR decisions, better workforce planning, salary management, and organizational performance improvement

# Domain
Human Resources

#**Dataset Information**

**Source:** Kaggle / <font color="blue"><u> **https://www.kaggle.com/datasets/desolution01/messy-employee-dataset</font></u>


**Dataset Column/features Description:**

**Employee_ID**:Unique identification number assigned to each employee

**First_Name**:First name of the employee

**Last_Name**:Last name of the employee

**Age:**:Age of the employee

**Department_Region**:Department and geographical region of the employee

**Status**: Current employee status such as Active, Inactive, or Pending

**Join_Date**:	Date on which the employee joined the organization

**Salary**:Annual salary of the employee

**Email**:Employee email address

**Phone**:Employee phone number

**Performance_Score**:Employee performance rating such as Poor, Average, Good, or Excellent

**Remote_Work**:Indicates whether the employee works remotely

# Stages for DA Project
**Problem Definition and Dataset Selection **

**NOTE: THINGS TO BE COMPLETED**

To analyze employee demographics, department and regional distribution, salary patterns, performance, employment status, and remote-work trends to identify useful HR and workforce insights.

Outcome:

To help the organization improve workforce planning, employee performance, salary management, employee retention, and overall HR decision-making.

The dataset describes an employee/workforce dataset containing employee identification, personal information, department, region, employment status, joining date, salary, performance score, and remote-work information

Import libraries, load dataset

Dataset description (rows, columns, features)

Initial EDA (head, info, describe, shape, null checks, duplicate check

# **Inital EDA**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("https://raw.githubusercontent.com/jagadishstarc-coder/Main-Project-/refs/heads/main/Main%20Project%20Raw%20Data.csv")

#Display first 5 rows
df.head()

#Display last 5 rows in the dataset
df.tail()

#Display no.of rows and columns
df.shape

#Display no.of rows and columns
df.columns

df.dtypes

#Display Information about the dataset
df.info()

#Generate Descriptive Statistics
df.describe()

# Check missing values in each column
df.isnull().sum()

print(df.isnull())

# Check duplicate records
print(df.duplicated().sum())

# Display duplicate records
df[df.duplicated()]

print(df.isna())

print(df.isna().sum())

print(df.ndim)

print(df.notna())

print(df.notna().sum())

df['Employee_ID'].duplicated().sum()

df[df['Employee_ID'].duplicated()]

#Count the unique values in Employee_ID
print(f'unique values in Employee_ID = {df['Employee_ID'].nunique()}')

"""## Stage 2 – Data Cleaning and Pre-processing

- Handle missing values (impute or drop)

- Handle duplicates
- column name rename or dropping unwanted columns if required

- Treat outliers if required

- Check skewness and apply transformations

- Convert data types if needed

- Feature transformations (date parts, derived fields if required for analysis
"""

#Dropping the duplicate rows in Employee_IDdf = df.drop_duplicates(subset=['Employee_ID'])

#Dropping the na rows in Employee_ID
df = df.dropna(subset=['Employee_ID'])

#Counting the rows and columns after removing duplicate rows
df.shape

#Displaying the NA / null values
df[df['Employee_ID'].isna()]

#Displaying the NA / null values as sum
df.isnull().sum()

# Import required libraries
import pandas as pd

# Load the Employee dataset
df = pd.read_csv(
    "https://raw.githubusercontent.com/jagadishstarc-coder/Main-Project-/refs/heads/main/Main%20Project%20Raw%20Data.csv"
)

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Clean and standardize Employee_ID
df["Employee_ID"] = (
    df["Employee_ID"]
    .astype("string")
    .str.strip()
)

# Clean and standardize First_Name
df["First_Name"] = (
    df["First_Name"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Clean and standardize Last_Name
df["Last_Name"] = (
    df["Last_Name"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Convert Age to numeric
df["Age"] = pd.to_numeric(
    df["Age"],
    errors="coerce"
)

# Clean Department_Region
df["Department_Region"] = (
    df["Department_Region"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Clean Status
df["Status"] = (
    df["Status"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Convert Join_Date to datetime
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
)

# Convert Salary to numeric
df["Salary"] = pd.to_numeric(
    df["Salary"],
    errors="coerce"
)

# Clean Email
df["Email"] = (
    df["Email"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Clean Phone
df["Phone"] = (
    df["Phone"]
    .astype("string")
    .str.strip()
)

# Convert Performance_Score to numeric
df["Performance_Score"] = pd.to_numeric(
    df["Performance_Score"],
    errors="coerce"
)

# Clean Remote_Work
df["Remote_Work"] = (
    df["Remote_Work"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Display the cleaned dataset
display(df.head())

# Fill missing age values with the median age and convert the column to integer
df['Age'] = df['Age'].fillna(df['Age'].median()).astype(int)

# Display the minimum age
print("Minimum Age:", df['Age'].min())

# Display the maximum age
print("Maximum Age:", df['Age'].max())

# Display all unique age values
print("Unique Age:", df['Age'].unique())

# Calculate and display the median age
print("Median Age:", df['Age'].median())

# Replace outlier age values (<10 or >100) with the median age
df.loc[(df['Age'] < 10) | (df['Age'] > 100), 'Age'] = df['Age'].median()

print("Minimum Age:", df['Age'].min())
print("Maximum Age:", df['Age'].max())
print("unique Age:", df['Age'].unique())

# Replacing invalid values in Status column
df['Status'] = df['Status'].replace({
    'A': 'Active',
    'I': 'Inactive',
    'P': 'Pending'
})

print(f'Unique values in Status = {df['Status'].unique()}')

print(f'Counting null values in Status after cleaning = {df['Status'].isna().sum()}')

print(f"Unique values in Department_Region = {df['Department_Region'].unique()}")

print(f'Counting null values in Department_Region after cleaning = {df['Department_Region'].isna().sum()}')

print(f'Unique values in Remote_Work = {df['Remote_Work'].unique()}')

print(f'Counting null values in Remote_Work = {df['Remote_Work'].isnull().sum()}')

print(f'Unique values in Performance_Score = {df['Performance_Score'].unique()}')

print(f'Counting null values in Performance_Score after cleaning = {df['Performance_Score'].isnull().sum()}')

print(f'Counting null values in Salary Before cleaning = {df['Salary'].isnull().sum()}')

# Fill missing Salary values with the median Salary for each Performance Score based on Group by and converting the column to integer type
df['Salary'] = df['Salary'].fillna(
    df.groupby('Performance_Score')['Salary'].transform('median')
).fillna(df['Salary'].median()).astype(int)

print(f'Minimum value = {df['Salary'].min()}')
print(f'Maximum value = {df['Salary'].max()}')
print(f'Unique values in Performance_Score = {df['Salary'].unique()}')

# Replace invalid Salary values (<=0 or >10)
# with the median Salary for each Performance_Score group

invalid_salary = (df['Salary'] <= 0) | (df['Salary'] > 10)

df.loc[invalid_salary, 'Salary'] = (
    df.groupby('Performance_Score')['Salary']
      .transform('median')[invalid_salary]
)

print(df['Age'].min())
print(df['Age'].max())
print(df['Age'].unique())

# Fill missing unit price values with the median unit price based on grouping Performance_Score
df['Salary'] = df['Salary'].fillna(df.groupby('Salary')['Salary'].transform('median'))

# Round unit price values to 2 decimal places
df['Salary'] = df['Salary'].round(2)

print(f'Counting null values in Unit Price after cleaning = {df['Salary'].isnull().sum()}')

print(f'Minimum value = {df['Age'].min()}')
print(f'Maximum value = {df['Age'].max()}')

print(f'Unique values in Remote_Work after Cleaning= {df['Remote_Work'].unique()}')

print(f'Counting null values in Remote_Work  = {df['Remote_Work'].isnull().sum()}')

print(f'Minimum Value = {df['Salary'].min()}')
print(f'Maximum Value = {df['Salary'].max()}')
print(f'Counting Unique values in Salary= {df['Salary'].unique()}')

df.isnull().sum()

# Convert Employee IDs to uppercase for consistent formatting
df['Employee_ID'] = df['Employee_ID'].str.upper()

df.to_csv("updated_messy_employee_dataset.csv", index=False)

from google.colab import files

files.download("updated_messy_employee_dataset.csv")

"""## Stage 3 – EDA and Visualizations

Univariate Analysis → distribution of single variables (countplot, histogram, boxplot)

Bivariate Analysis → relation between two variables (scatterplot, barplot, correlation heatmap)

Multivariate Analysis → relation among 3+ variables (pairplot, grouped analysis, pivot tables, advanced plots)

**Interpretation MUST with every visualization**

Focus on business story not just charts

Each chart must be in seperate cells.
"""

# Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
df1 = pd.read_csv(
    "https://raw.githubusercontent.com/jagadishstarc-coder/Main-Project-/refs/heads/main/Main%20Project%20Raw%20Data.csv"
)

# Age count plot
sns.countplot(
    data=df1,
    x='Age',
    order=sorted(df1['Age'].dropna().unique())
)

# Title and labels
plt.title('Age', fontsize=16, fontname='Arial')
plt.xlabel('Age', fontsize=12, fontname='Arial')
plt.ylabel('Number of Employees', fontsize=12, fontname='Arial')

# Rotate x-axis labels
plt.xticks(rotation=45)

# Adjust layout
plt.tight_layout()

# Show chart
plt.show()

"""#Interpretation

This bar chart shows the distribution of employees across different age categories. It represents the number of employees belonging to each age group: 25, 30, 35, and 40 years. The employee distribution is relatively balanced across the age categories, with only moderate differences in employee counts.

Features in the Chart:

This chart uses two features from the dataset: Age and Employee Count.
Age is a numerical variable representing the employee's age, while Number of Employees represents the number of employees belonging to each age category.

Key Insights:

Employees aged 40 have the highest count, with approximately 210 employees.
Employees aged 25 account for approximately 207 employees.
Employees aged 30 account for approximately 206 employees.
Employees aged 35 have the lowest count, with approximately 188 employees.
The difference between the highest and lowest employee counts is relatively small.
Overall, the workforce is fairly evenly distributed across the four age categories.

Business Recommendations:

Maintain a balanced workforce across different age groups.
Provide training and development opportunities that are suitable for employees across different age categories.
Encourage knowledge sharing and collaboration between employees of different age groups.
Consider age diversity when planning employee engagement, career development, and workforce strategies
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("https://raw.githubusercontent.com/jagadishstarc-coder/Main-Project-/refs/heads/main/Main%20Project%20Raw%20Data.csv")

sns.histplot(data=df, x='Salary', bins=20)

plt.title('Employees by Salary', fontsize=16, fontname='Arial')
plt.xlabel('Salary', fontsize=12, fontname='Arial')
plt.ylabel('Number of Employees', fontsize=12, fontname='Arial')

plt.show()

"""# Interpretation

This chart shows the distribution of employees by salary. It represents the number of employees falling within different salary ranges. The salaries in the dataset range approximately from $50,000 to $120,000. Overall, the number of employees is fairly distributed across the different salary ranges.

Features in the Chart

This chart uses two features from the dataset:

* Salary – represents the salary earned by employees.
* Number of Employees – represents how many employees fall within each salary range.

The histogram divides the salary values into 20 different ranges (bins).

Key Insights

Employee salaries range approximately from $50,000 to $120,000.
The highest number of employees is concentrated around the $90,000–$100,000 salary range.The number of employees varies across different salary ranges.
Some salary ranges have approximately 35–45 employees, while others have more than 60 employees.The distribution does not show a strong concentration at only one salary level.Overall, employees are distributed across a wide range of salary levels.

Business Recommendations

Analyze employee salaries to understand the organization’s salary structure.
Review salary ranges where employee concentration is particularly high.Compare salaries with job roles, experience, and performance to ensure appropriate compensation.Use salary distribution analysis to support budget planning and workforce management.Identify unusually low or high salary ranges that may require further investigation
"""

# Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
df1 = pd.read_csv(
    "https://raw.githubusercontent.com/jagadishstarc-coder/Main-Project-/refs/heads/main/Main%20Project%20Raw%20Data.csv"
)

# Remove extra spaces from column names
df1.columns = df1.columns.str.strip()

# Create Remote Work count plot
plt.figure(figsize=(10, 7))

ax = sns.countplot(
    data=df1,
    x='Remote_Work'
)

# Title and labels
plt.title(
    'Number of Employees by Remote Work',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('Remote Work', fontsize=12)
plt.ylabel('Number of Employees', fontsize=12)

# Add employee counts on top of bars
for container in ax.containers:
    ax.bar_label(container, padding=3)

plt.tight_layout()
plt.show()

"""#Interpretation

This bar chart shows the Number of employees based on their remote work status. It represents the number of employees who belong to each Remote Work category. The chart shows that 507 employees are in one remote-work category and 513 employees are in the other category.

Overall, the Number of employees between the two remote-work categories is fairly balanced, with only a small difference of 6 employees.

Features in the Chart

This chart uses two features from the dataset:

* Remote Work – a categorical variable indicating whether an employee works remotely or not.
* Employee Count – represents the number of employees in each remote-work category.

Key Insights

One Remote Work category contains approximately 507 employees.
The other Remote Work category contains approximately 513 employees.
The difference between the two categories is only 6 employees.
Overall, employees are almost evenly distributed between the two remote-work categories.

Business Recommendations

Maintain flexible work policies based on employee and business requirements.
valuate employee productivity and satisfaction across remote and non-remote work arrangements.Provide appropriate technical support and communication tools for remote employees.
Continue monitoring remote-work trends to support effective workforce planning.
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(data=df, x='Department_Region')

plt.title('Employees by Department Region', fontsize=16, fontweight='bold')
plt.xlabel('Department Region', fontsize=12)
plt.ylabel('Number of Employees', fontsize=12)

plt.xticks(rotation=45)
plt.show()

"""#Interpretation:
This bar chart shows the numbers of employees across different Department-Region categories. It represents the number of employees associated with each combination of department and region.The chart shows that the number of employees varies across the different Department-Region categories. Most categories have employee counts ranging approximately from 20 to 35, while a few categories have higher or lower employee counts

Features in the Chart

This chart uses two features from the dataset:

Department_Region – a categorical variable representing the combination of an employee’s department and region.
Number of Employees – represents the count of employees belonging to each Department-Region category.

Key Insights

Employee distribution varies across the different Department-Region categories.
Most Department-Region categories contain approximately 20–35 employees.
One category has the highest employee count, with approximately 41 employees.
Some categories have relatively fewer employees, with the lowest category containing approximately 16 employees.
Overall, employee counts are distributed across many different Department-Region categories rather than being concentrated in only one category.

Business Recommendations

Monitor employee distribution across departments and regions to identify areas with higher or lower staffing levels.
Consider workforce planning based on the employee count in each Department-Region category.
Departments or regions with comparatively low employee counts can be reviewed to determine whether additional staffing is required.
Higher-employee categories should be monitored to ensure workloads and resources are appropriately managed.
Use Department-Region data to support recruitment, resource allocation, and workforce planning decisions
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(data=df, x='Status')

plt.title('Employees by Status', fontsize=16, fontweight='bold')
plt.xlabel('Status', fontsize=12)
plt.ylabel('Number of Employees', fontsize=12)

plt.xticks(rotation=45)
plt.show()

"""#Interpretation

This bar chart shows the Numbers of employees by status. It represents the number of employees belonging to each status category: Active, Pending, and Inactive. Overall, the employee distribution is relatively balanced between Active and Pending employees, while the number of Inactive employees is somewhat lower.

Features in the Chart

This chart uses two features from the dataset: Status and Employee Count. Status is a categorical variable containing Active, Pending, and Inactive, while Employee Count represents the number of employees in each status category.

Key Insights

Pending employees have the highest count, with approximately 355 employees. Active employees account for approximately 352 employees.Inactive employees account for approximately 312 employees.The difference between the highest and lowest employee counts is relatively small.Overall, the employee status distribution is fairly balanced, although the Inactive category has fewer employees.

Business Recommendations

Monitor the Pending employee category to understand why employees remain in pending status.
Continue supporting Active employees through engagement and retention initiatives.
Analyze the reasons for employees becoming Inactive and identify opportunities to improve retention.
Use employee-status trends to support workforce planning and HR decision-making
"""

sns.scatterplot(
    data=df,
    x='Performance_Score',
    y='Department_Region'
)

plt.title('Department_Region vs Performance_Score', fontsize=16, fontweight='bold')
plt.xlabel('Performance_Score')
plt.ylabel('Department_Region')

plt.show()

"""# Interpretation

This scatter plot shows the relationship between Department_Region and Performance_Score. It represents employees across different department-region combinations and their corresponding performance score categories. The performance scores are classified into Average, Excellent, Good, and Poor.

Features in the Chart

This chart uses two features from the dataset:

Performance_Score – a categorical variable containing Average, Excellent, Good, and Poor.
Department_Region – a combined categorical variable representing the employee’s department and region, such as DevOps-California, Finance-Texas, HR-New York, etc.

Key Insights

The chart contains four performance categories: Average, Excellent, Good, and Poor.Employees are distributed across multiple department-region combinations.
Each performance category contains observations from different departments and regions.The vertical arrangement shows that Department_Region is categorical, so the scatter plot is mainly useful for visualizing the distribution of department-region observations across performance categories.The chart does not directly show the number of employees in each category.To determine which department or region has the highest/lowest performance, the underlying data should be grouped and summarized.

Business Recommendations

Analyze performance scores separately for each department and region.
Identify department-region combinations with a high proportion of Excellent or Good performance.Investigate areas where Poor performance is more common.
Compare departments across different regions to identify performance differences.Use the results for targeted employee development and workforce planning
"""

plt.figure(figsize=(12, 7))

sns.countplot(
    data=df1,
    x='Department_Region',
    hue='Age'
)

plt.title('Department Region vs Age', fontsize=16)
plt.xlabel('Department Region', fontsize=12)
plt.ylabel('Number of Employees', fontsize=12)

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""# Interpretation

This bar chart shows the Numbers of employees across different Department-Region categories based on their age groups. It represents the number of employees belonging to different age categories such as 25, 30, 35, and 40 years within each Department-Region.

Features in the Chart

This chart uses two main features from the dataset:

Department_Region – A categorical variable representing the combination of an employee’s department and region.
Age – A numerical/categorical variable representing the age of employees.

The Number of Employees is represented by the height of each bar.

Key Insights

Employees are distributed across different Department-Region categories and age groups.
The chart includes age categories such as 25, 30, 35, and 40 years.
Some Department-Region categories have a higher number of employees in particular age groups.
The employee distribution varies between different Department-Region combinations.
Certain age groups, particularly 30, 35, and 40, show relatively higher employee counts in several Department-Region categories.The chart helps identify which age groups are more common within different Department-Region combinations.

Business Recommendations

Analyze employee distribution by Department and Region to understand workforce composition.
Consider age distribution when planning workforce development and training programs.
Departments with fewer employees in particular age groups can be reviewed for recruitment and workforce planning.
Use the age and department-region information to support employee retention and succession planning.
Maintain a balanced workforce across departments and regions to support long-term organizational requirements
"""

# Make a copy of the required columns
df_corr = df1[
    [
        'Age',
        'Salary',
        'Performance_Score'
    ]
].copy()

# Convert Performance_Score to numeric
# Text values such as "Average" will become NaN
df_corr['Performance_Score'] = pd.to_numeric(
    df_corr['Performance_Score'],
    errors='coerce'
)

# Convert Age and Salary to numeric as well
df_corr['Age'] = pd.to_numeric(df_corr['Age'], errors='coerce')
df_corr['Salary'] = pd.to_numeric(df_corr['Salary'], errors='coerce')

# Calculate correlation
correlation = df_corr.corr()

# Create heatmap
plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f',
    linewidths=0.5
)

plt.title(
    'Correlation Heatmap',
    fontsize=16,
    fontweight='bold'
)

plt.tight_layout()
plt.show()

"""# Interpretation

The correlation heatmap shows the relationship between Age, Salary, and Performance Score of employees. Correlation values range from -1 to +1, where a value closer to +1 indicates a positive relationship, a value closer to -1 indicates a negative relationship, and a value near 0 indicates a weak relationship.

Features in the Chart

This chart uses three numerical features from the employee dataset: Age, Salary, and Performance Score. These variables are used to identify whether there is a relationship between employees’ age, salary, and performance.

Key Insights

Age and Salary have a correlation of approximately 0.09, indicating a very weak positive relationship.
This suggests that employee age has very little linear relationship with salary in this dataset.
The diagonal values are 1.00 because each variable has a perfect correlation with itself.
Performance Score can be included in the correlation analysis after converting it into numerical values, as shown in the Python code.
Overall, the heatmap helps identify whether employee age, salary, and performance are related to each other.

Business Recommendations

Organizations should not rely only on age when making salary-related decisions, since the correlation between age and salary is very weak in this dataset. Salary and performance can be analyzed together to understand whether higher-performing employees are appropriately compensated. Employee development, experience, skills, and performance should be considered when reviewing compensation and career-growth decisions
"""

sns.pairplot(
    df1[['Age', 'Department_Region', 'Salary', 'Status', 'Remote_Work']]
)

plt.show()

"""# Interpretation

The charts provide an overview of the employees/customers based on key demographic, organizational, salary, employment-status, and work-location characteristics. The analysis focuses on Age, Department, Region, Salary, Status, and Remote Work to understand how these variables are distributed across the dataset.

Features in the Charts

The analysis uses several important features from the dataset:

Age – represents the age of employees/customers.
Department – represents the department or functional area in which they work.
Region – represents the geographical region of the employees/customers.
Salary – represents the salary associated with each employee/customer.
Status – represents the current employment or customer status.
Remote Work – indicates whether the employee works remotely or follows an on-site/hybrid arrangement.

Key Insights

Age:
The age distribution helps identify the different age groups represented in the dataset and provides an understanding of the overall workforce/customer profile.

Department:
The department distribution shows how employees are spread across different organizational functions. It can help identify departments with relatively higher or lower representation.

Region:
The regional distribution provides information about the geographical spread of employees/customers. It can be used to understand which regions contribute more significantly to the dataset.

Salary:
Salary analysis provides an understanding of the overall compensation pattern. The correlation heatmap shows a weak positive relationship between Age and Salary (approximately 0.09), indicating that age and salary have only a limited linear relationship in this dataset.

Status:
Status indicates the current condition or employment category of individuals in the dataset. Comparing the different status categories can help understand workforce/customer composition.

Remote Work:
Remote-work information shows how employees are distributed between remote and non-remote working arrangements. This can provide useful insight into the organization’s working model.

Business Recommendations

Organizations can use these insights to better understand their workforce/customer structure. Age and salary should be analyzed together with department, region, status, and remote-work patterns rather than relying on a single variable. Departments and regions with lower representation can be examined for workforce planning, while salary patterns can support compensation analysis. Remote-work data can also help organizations evaluate and plan appropriate workplace policies.Overall, the analysis provides a clear view of the relationship and distribution of Age, Department, Region, Salary, Status, and Remote Work, supporting data-driven workforce and business planning.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Create pivot table
pivot = pd.crosstab(
    df1['Remote_Work'],
    df1['Status']
)

# Create bar chart
pivot.plot(
    kind='bar',
    figsize=(12, 7)
)

# Chart title
plt.title(
    'Total Employees by Remote Work and Status',
    fontsize=16,
    fontweight='bold'
)

# Axis labels
plt.xlabel('Remote Work', fontsize=12)
plt.ylabel('Number of Employees', fontsize=12)

# Rotate x-axis labels
plt.xticks(rotation=45)

# Legend
plt.legend(title='Status')

# Adjust layout
plt.tight_layout()

# Display chart
plt.show()

"""# Interpretation

This bar chart shows the total number of employees based on Remote Work and Employment Status. It compares employees working under different remote-work arrangements and shows how many employees are Active, Inactive, and Pending in each category.

Features in the Chart

This chart uses two main features from the dataset: Remote Work and Status.

Remote Work represents the employee’s work arrangement, such as remote or non-remote work.
Status represents whether an employee is Active, Inactive, or Pending.
Number of Employees represents the total employees in each combination of remote-work arrangement and status.

Key Insights

For the first remote-work category, there are approximately 168 Active employees, 152 Inactive employees, and 188 Pending employees. Pending employees represent the largest group in this category.

For the second remote-work category, there are approximately 185 Active employees, 160 Inactive employees, and 169 Pending employees. Active employees represent the largest group in this category.

Overall, the chart shows that employee status varies across remote-work arrangements. Active, Inactive, and Pending employees are all represented in substantial numbers, with some differences between the two remote-work categories.

Business Recommendations

Organizations can use this information to monitor workforce status across different remote-work arrangements. Management should pay attention to Pending employees and review their employment status regularly. The differences between remote and non-remote employees can also support workforce planning, staffing decisions, and remote-work policy development
"""

# Count total employees by Department_Region and Age
department_age = (
    df1.groupby(['Department_Region', 'Age'])
       .size()
       .reset_index(name='Total_Employees')
       .sort_values('Total_Employees', ascending=False)
)

# Display the result
display(department_age)

# Create bar chart
plt.figure(figsize=(14, 8))

sns.barplot(
    data=department_age,
    x='Total_Employees',
    y='Department_Region',
    hue='Age',
    palette='viridis'
)

# Title
plt.title(
    'Total Employees by Department Region and Age',
    fontsize=16,
    fontweight='bold'
)

# Axis labels
plt.xlabel('Total Employees', fontsize=12)
plt.ylabel('Department Region', fontsize=12)

plt.legend(
    title='Age',
    bbox_to_anchor=(1.05, 1),
    loc='upper left'
)

plt.tight_layout()
plt.show()

"""# Interpretation

This bar chart shows the total number of employees by Department, Region, and Age. It represents how employees are distributed across different department-region combinations, with the different colored bars showing employee counts for each age group.

Features in the Chart

This chart uses three main features from the dataset:

Department – represents the functional area, such as HR, Sales, Finance, Admin, DevOps, and Cloud Tech.
Region – represents the geographical location, such as Florida, New York, Nevada, Illinois, Texas, and California.Age – represents the age category of employees.Total Employees – represents the number of employees belonging to each Department-Region-Age combination.

Key Insights

The chart shows that employee counts vary considerably across different departments, regions, and age groups. Some Department-Region combinations have noticeably higher employee counts, while others have lower representation.

HR-Florida shows one of the highest employee counts among the combinations displayed. Sales-New York, Sales-Nevada, DevOps-Illinois, and DevOps-Texas also have relatively high employee representation in particular age groups.

The distribution of employees across age groups is not identical for every department and region. Some combinations have stronger representation in certain age groups, indicating that the workforce composition differs depending on both department and geographical region.

Overall, the chart demonstrates that employee distribution is influenced by the combination of department, region, and age, rather than being evenly distributed across all categories.

Business Recommendations

Organizations can use this information to identify departments and regions with higher or lower employee representation. Workforce planning can be adjusted according to the age composition of each department and region. Departments with lower employee counts may require additional recruitment, while departments with higher representation can be monitored for workforce capacity and resource allocation.
"""

# Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Remove extra spaces from column names
df1.columns = df1.columns.str.strip()

# Split Department_Region into Department and Region
df1[['Department', 'Region']] = df1['Department_Region'].str.split(
    '-', n=1, expand=True
)

# Remove extra spaces from Department and Region
df1['Department'] = df1['Department'].str.strip()
df1['Region'] = df1['Region'].str.strip()

# Convert Salary to numeric
df1['Salary'] = pd.to_numeric(
    df1['Salary'],
    errors='coerce'
)

# Calculate total salary by Region and Department
region_department_salary = (
    df1.groupby(
        ['Region', 'Department'],
        as_index=False
    )
    .agg(Total_Salary=('Salary', 'sum'))
    .sort_values(
        'Total_Salary',
        ascending=False
    )
)

# Convert salary into ₹ Lakhs
region_department_salary['Total_Salary_Lakhs'] = (
    region_department_salary['Total_Salary'] / 100000
).round(2)

# Display result
display(region_department_salary)

# Create bar chart
plt.figure(figsize=(14, 8))

sns.barplot(
    data=region_department_salary,
    y='Department',
    x='Total_Salary_Lakhs',
    hue='Region'
)

# Chart title
plt.title(
    'Total Salary by Department and Region',
    fontsize=16,
    fontweight='bold'
)

# Axis labels
plt.xlabel('Total Salary (₹ Lakhs)', fontsize=12)
plt.ylabel('Department', fontsize=12)

# Legend
plt.legend(
    title='Region',
    bbox_to_anchor=(1.02, 1),
    loc='upper left'
)

plt.tight_layout()
plt.show()

"""# Interpretation
This bar chart shows the distribution of total salary by department and region. It compares the combined salary amounts for different departments across six regions: Florida, California, Nevada, New York, Illinois, and Texas. The chart helps identify which regions contribute the highest total salary within each department and shows how salary distribution varies across departments.

Features in the Chart

This chart uses two main features from the dataset: Department, Region, and Salary.

Department represents departments such as HR, Sales, and Admin.
Region represents the geographical regions: Florida, California, Nevada, New York, Illinois, and Texas.
Total Salary represents the sum of salaries for employees within each department and region.

Key Insights

HR: New York has the highest total salary among the displayed regions, while Texas has a comparatively lower total salary.
 Sales: Florida has the highest total salary, followed by Nevada and California. Texas has a comparatively lower total salary.
Admin: California records the highest total salary, followed by Nevada and Illinois.
Overall, total salary varies considerably by both department and region.
Some regions show consistently higher salary totals across multiple departments, indicating a larger salary contribution from those regions.
The comparison helps identify areas where employee salary costs are concentrated.

Business Recommendations

Organizations can use this analysis to monitor salary expenses across departments and regions. Departments or regions with particularly high total salary costs can be reviewed to understand workforce size, compensation levels, and staffing requirements. Management can also use these insights for budget planning, salary allocation, workforce planning, and regional cost control

## **Steps to Download your cleaned data for dashboard creation using Power BI**
"""

#import pandas as pd
#df=pd.read_csv("https://raw.githubusercontent.com/jagadishstarc-coder/Main-Project-/refs/heads/main/Main%20Project%20Raw%20Data.csv")
df.to_csv("insurance.csv")

"""## Stage 4 – Documentation, Insights and Presentation

Show a dashboard aligning all the charts in powerbi by connecting python in PowerBI

Summarize findings in plain English (what do the patterns mean)

Highlight 3–5 key insights (trends, anomalies, correlations)

Provide recommendations for business or decision-making

Explain the FINAL STORY WITH THE DASHBOARD/report

Create a PDF pasting your DASHBOARD, explaining all the above mentioned concepts and submit it
"""

from google.colab import files
from IPython.display import display
from PIL import Image
import io

# Upload dashboard images
uploaded = files.upload()

# Display all uploaded images
for filename, filedata in uploaded.items():
    print(f"Dashboard: {filename}")
    display(Image.open(io.BytesIO(filedata)))

from google.colab import files
from IPython.display import display
from PIL import Image
import io

# Upload dashboard images
uploaded = files.upload()

# Display all uploaded images
for filename, filedata in uploaded.items():
    print(f"Dashboard: {filename}")
    display(Image.open(io.BytesIO(filedata)))

"""## **Final Overall Insights:**

Descriptive Analysis

The Employee Analytics Dashboard contains 1,020 employees with an average age of 32.48 years. There are 352 active employees, while 356 employees are pending and 312 are inactive. The total salary expenditure is approximately 86.86M. Among departments, DevOps has the highest employee count, followed by Sales and HR, while Cloud Tech has the lowest. Regionally, California and Florida have the highest employee counts, while Texas has the lowest among the displayed regions. The workforce is almost evenly divided between remote employees (513) and non-remote employees (507). Performance ratings are relatively balanced, with Good having the highest count, followed by Average and Excellent, while Poor has the lowest count.

Diagnostic Analysis

The dashboard indicates several areas that require further investigation. The number of pending employees (356) is slightly higher than active employees, which may indicate delays in onboarding, approval, or employee-status processes. The Poor performance category accounts for 216 employees, suggesting a significant group may require training, performance support, or closer evaluation. Employee numbers increased significantly in 2023, reaching 228 employees, before declining slightly to 217 in 2024. Salary distribution also varies across department-region combinations, indicating that workforce size, department, location, and salary structure should be examined together. The almost equal distribution of remote and non-remote employees suggests that remote work is an important component of the organization’s workforce structure.

Predictive Analysis

Historical employee and joining-year trends can be used to forecast future workforce requirements and recruitment needs. The increase in employee numbers during 2023 followed by a slight decline in 2024 may indicate a changing hiring pattern that should be monitored. Performance-score data can help identify employees who may require future training or development programs. Department and regional employee counts can be used to predict future staffing requirements, while salary trends can support workforce budgeting and compensation planning. Remote-work patterns can also be monitored to forecast future workplace and infrastructure requirements.

Prescriptive Analysis

The organization should focus on reducing the number of pending employees by reviewing onboarding and approval processes. Employees in the Poor performance category should be provided with targeted training, mentoring, and performance-improvement programs. Since DevOps, Sales, and HR have relatively high employee counts, management should ensure adequate resources and workload distribution in these departments. Recruitment and workforce planning should consider the higher employee concentrations in California and Florida. Salary expenditure should be analyzed by department, region, and employee performance to identify opportunities for better compensation planning. Finally, the nearly equal split between remote and non-remote employees supports maintaining a flexible work strategy while continuously evaluating productivity and employee performance.

# Future Enhancement


#Business Insights & Recommendations – Employee Analysis Dashboard

● Employee Status Management: Analyze Active, Pending, and Inactive employees to understand workforce availability and identify reasons for inactive or pending status. Develop strategies to improve employee retention and workforce stability.

● Employee Performance Improvement: Monitor Performance Score categories such as Good, Average, Excellent, and Poor. Identify employees or departments with lower performance and provide targeted training, support, and development programs.

● Department & Regional Workforce Optimization: Analyze employee distribution across Departments and Regions to identify areas with high or low workforce concentration. Optimize staffing levels according to business requirements.

● Salary & Compensation Analysis: Compare total salary across departments, regions, and age groups to identify salary patterns and ensure compensation is aligned with employee performance, experience, and organizational requirements.

● Employee Retention & Workforce Planning: Analyze Employee Join Year trends to understand hiring patterns and workforce growth. Use these insights for future recruitment, succession planning, and employee retention strategies.

● Remote Work Optimization: Analyze Remote Work status across employee groups, departments, and regions to understand the balance between remote and non-remote employees and develop effective workplace policies.

● Age & Workforce Demographics: Examine employee age distribution and salary by age category to understand workforce demographics and support effective workforce planning.

● Performance & Compensation Relationship: Compare Performance Score with Salary, Department, Region, and Age to identify whether compensation and performance are appropriately aligned.

● Regional Workforce Strategy: Analyze employee counts and performance across regions such as California, Florida, Nevada, Illinois, New York, and Texas to identify regional workforce strengths and areas requiring improvement.

● Data-Driven HR Decision Making: Use dashboard insights on employee status, performance, salary, department, region, joining year, age, and remote work to support strategic HR decisions, improve productivity, control workforce costs, and plan future staffing needs

# Conclusion

Conclusion

The Employee Analytics Dashboards provide a comprehensive overview of workforce composition, employee performance, salary distribution, employee status, remote work, departments, regions, and joining trends.

The organization has 1,020 employees, including 352 active employees, with an overall average age of 32.48 years and total salary expenditure of approximately 86.86M. The dashboards show that DevOps, Sales, HR, Finance, Admin, and Cloud Tech contribute significantly to the workforce.

Employee status analysis highlights the distribution between Active, Pending, and Inactive employees, while performance analysis shows employees categorized as Good, Average, Excellent, and Poor. Remote-work analysis also provides insights into the balance between employees working remotely and those working on-site.

The dashboards further help identify regional workforce patterns, salary differences by department and region, employee joining trends by year, age-wise salary distribution, and performance trends over time.

Overall, these insights can support data-driven HR decisions, including workforce planning, employee retention, performance improvement, salary management, recruitment strategy, and optimizing remote-work policies
"""